### ISSUE TITLE
Depth map goes 100% black periodically during debug export (VDA_L)

### ISSUE THREAD

**Issue by enoky** [nagadomi/nunif#397]
First, thank you for all the work you've put into the iw3 project! The community loves you :)

I tried to output a full movie as debug depth (with VDA_L) and there are many spots throughout the movie that are 100% black in spots where it shouldn't be.

Just wanted to bring this to your attention.

Cheers!

**Comment by enoky** [comment]
Someone on discord mentioned the function: compute_scale_and_shift

**Comment by nagadomi** [comment]
I also found a bug that Scene Segmentation not working properly only when using VDA.
I will fix this later, but it will not occur if Batch Size=1.

**Comment by nagadomi** [comment]
>I also found a bug that Scene Segmentation not working properly only when using VDA.

I fixed this in the dev branch.

Also, `Lookahed Buffer Size` (--ema-buffer, right combobox) was added as an option for Flicker Reduction.
This calculates the depth range over a specified number of future frames starting from the current frame.

I haven't tested it much yet.
A conservative setting is: `Decay Rate = 0.75, Buffer Size = 30`.
With Buffer Size = 30, the depth range is calculated over 1 second at 30 FPS. Buffer Size = 150 means looking ahead 5 seconds. Buffer Size = 1 is the same as in the previous version.
As for Decay Rate, values above 0.9 might be too high. if it's too high, clipping may occur.

Also this option is currently only used in the VDA models (`VDA_S`, `VDA_L`, `VDA_Metric`).
Support for all models is planned, but not yet implemented.

**Comment by QuickscopingFTW** [comment]
Some scenes are still broken whenever a new foreground object appears, I've tried every combo of decay rate and buffer size and it doesn't seem to make a difference, the only change is a higher buffer size goes completely black sooner, is there something I'm doing wrong? I am using 3D strength 5, convergence 0, your own size 0, both view, row_flow_v3, stereo width default, VDA_L, 640 res, foreground 0, edge fix 3, with scene segmentation on and also using fp16

**Comment by nagadomi** [comment]
Then it might be a model-side issue, not a problem with iw3's min-max normalization or scene segmentation.
I'll try to make a video that can reproduce the problem.

**Comment by nagadomi** [comment]
I've identified the cause: NaNs are being generated.
NaN (Not a Number) can occur due to invalid numerical operations like division by zero or overflow, and once it appears, it propagates and turns everything into NaN.
I have a few possible causes in mind, so I'll give fixing it a try.

**Comment by nagadomi** [comment]
Fixed in Video-Depth-Anything_iw3 repo.
I haven't updated the nunif repository, but running `update.bat` should apply the fix.

And,
This nan/inf problem is properly handled in the official VDA repository.
The problem happened because I considered the fix unnecessary :bow:

**Comment by QuickscopingFTW** [comment]
This seems to have fixed it! Thanks again for looking into it :)

**Comment by nagadomi** [comment]
Thanks for the confirmation.

Also, though it's unrelated to this issue, I plan to rename `Scene Segmentation` in the future, since it differs from the academic usage of the term and may cause confusion.

**Comment by enoky** [comment]
I can also confirm the update has fixed the depth blackout issue!

Thank you so much for the fast update ^_^

**Comment by RudiRastelli** [comment]
> running `update.bat` should apply the fix.
Where can i find 'update.sh' ?
